### ISSUE TITLE
Add ArtifexSoftware GhostPDL fonts from package

### ISSUE THREAD

**Issue by ronaldtse** [fontist/formulas#158]
The GhostScript GhostPDL package contains fonts licensed under the AFPL license, which are necessary for a PCL interpreter, and also as the base font set part of Adobe's PostScript Level 3.

The fonts are offered here:
* https://github.com/ArtifexSoftware/ghostpdl/tree/master/pcl/urwfonts

And they can be downloaded from the packages here:
* https://github.com/ArtifexSoftware/ghostpdl-downloads/releases

Under `pcl/urwfonts/*.ttf`.

A number of these fonts are already provided in the URW-35base-fonts package under a more open license. Do we have to allow users to choose from licenses if the font is provided in 2 differently licensed packages?

**Comment by ronaldtse** [comment]
Using Fontist 1.2.0, the `create-formula` command can't create the formula for this package:

```sh
$ fontist create-formula https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10030/ghostpdl-10.03.0.tar.gz
Downloading: 100% (93/93 MiB), 2.93 MiB/s, done.
~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:24:in `write': Is a directory @ rb_sysopen - /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/d20240402-18175-8xxwq4/ghostpdl-10.03.0/lcms2mt/Projects/mac/LittleCMS/LittleCMS.xcodeproj/xcuserdata/User.xcuserdatad/xcsc (Errno::EISDIR)
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:24:in `save_tar_file'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:10:in `block (3 levels) in extract'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:60:in `each'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:9:in `block (2 levels) in extract'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:27:in `new'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:8:in `block in extract'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:7:in `open'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/extractors/tar_extractor.rb:7:in `extract'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:200:in `extract_once'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:171:in `extract_to_directory'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:156:in `extract_recursively'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:209:in `extract_and_replace'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:161:in `block in extract_recursively'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:158:in `each'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:158:in `extract_recursively'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:131:in `extract_all'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:41:in `extract'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/excavate-0.3.7/lib/excavate/archive.rb:22:in `files'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/import/recursive_extraction.rb:75:in `extract_data'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/import/recursive_extraction.rb:70:in `ensure_extracted'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/import/recursive_extraction.rb:27:in `font_files'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/import/create_formula.rb:35:in `setup_files'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/import/create_formula.rb:23:in `builder'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/import/create_formula.rb:15:in `call'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/lib/fontist/cli.rb:182:in `create_formula'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/exe/fontist:7:in `block in <top (required)>'
	from ~/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fontist-1.20.0/exe/fontist:28:in `<top (required)>'
	from ~/.asdf/installs/ruby/3.2.2/bin/fontist:25:in `load'
	from ~/.asdf/installs/ruby/3.2.2/bin/fontist:25:in `<main>'
```
